language:
  - python

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get install -y libsndfile1

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd demo
  - python demo.py
