language: 
  - python

python:
  - "2.7"
  - "3.5"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

script: 
  - python demo.py