language: 
  - python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get install -y libsndfile1

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - bash download_vocoder.sh
  - python setup.py build_ext --inplace

script: 
  - python demo.py