environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

init:
  - ps: |
      Write-Output "*** Python $env:PYTHON_VERSION ***"
      $env:Path += ";$env:PYTHON_ROOT;$env:PYTHON_ROOT\Scripts"

install:
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes  --set changeps1 no
  - conda update -q conda
  - conda config --add channels pypi
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy cython wheel"
  - activate test-environment
  - python -m pip install --no-cache-dir -U pip
  - ps: |
      Write-Output "Installing requirements..."
      pip install -r requirements.txt

build_script:
  - git submodule update --init
  - pip install -e .

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      Set-Location "$env:APPVEYOR_BUILD_FOLDER\demo"
      python demo.py
      Set-Location "$env:APPVEYOR_BUILD_FOLDER"

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*
